export const types = Object.freeze({
    INCREMENT_ID: 'INCREMENT_ID',
    CHANGE_VALUE: 'CHANGE_VALUE',
    SET_BACK_COLOR: 'SET_BACK_COLOR',
    SET_TEXT_COLOR: 'SET_TEXT_COLOR',
    RESET_COLORS: 'RESET_COLORS',
    ADD_TASK: 'ADD_TASK',
    REMOVE_TASK: 'REMOVE_TASK',
    COMPLETE_TASK: 'COMPLETE_TASK',
})

// export const INCREMENT_ID = 'INCREMENT_ID';
// export const CHANGE_VALUE = 'CHANGE_VALUE';
// export const SET_BACK_COLOR = 'SET_BACK_COLOR';
// export const SET_TEXT_COLOR = 'SET_TEXT_COLOR';
// export const RESET_COLORS = 'RESET_COLORS';
// export const ADD_TASK = 'ADD_TASK';
// export const REMOVE_TASK = 'REMOVE_TASK';
// export const COMPLETE_TASK = 'COMPLETE_TASK';